@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Oct 21 16:31:52 +0100 2020
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto ef6ad96051c34993b38eb2167b613464 --incr --debug typical --relax --mt 2 -L axi_bram_ctrl_v4_1_3 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_7 -L sim_clk_gen_v1_0_2 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_behav xil_defaultlib.tb xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto ef6ad96051c34993b38eb2167b613464 --incr --debug typical --relax --mt 2 -L axi_bram_ctrl_v4_1_3 -L xil_defaultlib -L blk_mem_gen_v8_4_4 -L axi_infrastructure_v1_1_0 -L axi_vip_v1_1_7 -L sim_clk_gen_v1_0_2 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_behav xil_defaultlib.tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
